version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
  qlty: qltysh/qlty-orb@0.0.11

executors:
  default:
    docker:
      - image: cimg/ruby:3.2.2

jobs:
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - qlty/coverage_publish:
          files: ./coverage/.resultset.json

workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - rspec
